---
title: "ESCAPE Data Pulling"
author: "<h3>SOCR MIMIC-III Team</h3>"
date: "`r format(Sys.time(), '%B %Y')`"
output:
  html_document:
  highlight: tango
number_sections: yes
theme: default
toc: yes
toc_depth: 2
toc_float:
  collapsed: no
smooth_scroll: yes
---
  
*Libraries Used*
```{r message=F, warning=F}
library('bigrquery')     # Query data from Google BigQuery
library('knitr')         # Make knited tables ("kables")
library('kableExtra')    # Extra kable formatting options
library('ggplot2')       # Plotting library
library('ggpubr')        # More options for ggplot
library("dplyr")

# project = 'socr-mdp-mimic-analytics' # CHANGE THIS TO YOUR PROJECT ID
project = 'mimic-alantran'
```

# Load the cohort

```{r}
cohort = read.csv("data/new_cohort.csv") %>% select(-X, -ROW_ID, -SEQ_NUM, -ICD9_CODE, -DEATHTIME, -DISCHTIME.y) %>% rename(DISCHTIME = DISCHTIME.x)
```

The final cohort consists of `r nrow(cohort)` encounters.

# Data extraction

```{r message=F, warning=F}

get_itemids = function(label) {
  label = tolower(label)
  sql = paste0('SELECT * FROM [physionet-data.mimiciii_clinical.d_items] WHERE LOWER(label) LIKE "%',label, '%"')
  data = query_exec(sql, project=project)
  itemids = data$ITEMID
  
  sql = paste0('SELECT * FROM [physionet-data.mimiciii_clinical.d_labitems] WHERE LOWER(label) LIKE "%',label, '%"')
  data = query_exec(sql, project=project)
  itemids = c(itemids, data$ITEMID)
  
  return(itemids)
}

get_values_from_ids = function(itemids, hadm_id=c(), table) {
  if (length(itemids) == 0) {
    return(list())
  }
  sql = sprintf('SELECT * FROM [physionet-data.mimiciii_clinical.%s] WHERE itemid IN (%s) AND hadm_id IN (%s)', 
                table,
                paste0(itemids, collapse = ", "), 
                paste(hadm_id, collapse=", "))
  data = query_exec(sql, project=project, max_pages=1)
  # print(kable(data) %>% kable_styling(bootstrap_options = 'striped'))

  data
}

get_values = function(label, table='chartevents', col_name = label, orig_col = "VALUE") {
  return(get_values_from_ids(get_itemids(label), cohort$HADM_ID, table) %>% select(HADM_ID, !!orig_col) %>% rename(!!col_name := !!orig_col)) %>% distinct(HADM_ID, .keep_all = TRUE)
}
```

## BNP

```{r}
bnp = get_values("BNP", 'labevents', "BNP", "VALUE")
bnp$BNP[bnp$BNP == "GREATER THAN 70000"] = 70000
bnp$BNP[bnp$BNP == "GREATER THAN 70,000"] = 70000
bnp$BNP[bnp$BNP == ">70000"] = 70000
bnp$BNP[bnp$BNP == "DONE"] = 70000
bnp$BNP = as.numeric(bnp$BNP)
```

## Diuretics

```{r}
diuretic = get_values("lasix", "inputevents_mv", "DIURETIC", orig_col = "AMOUNT")
```

## Beta-blockers

```{r}
blocker = get_values("lol", "inputevents_mv", "BETABLOCKERS", "AMOUNT")
```

## CPR/Mechanical ventilation

```{r}
cpr_codes = c(9960, 9390, 967, 9670, 9671, 9672)
sql = sprintf('SELECT * FROM [physionet-data.mimiciii_clinical.procedures_icd] 
              WHERE icd9_code IN (%s) AND hadm_id IN (%s)', 
              paste0(cpr_codes, collapse = ", "), 
              paste0(cohort$HADM_ID, collapse=", "))
cpr = query_exec(sql, project=project, max_pages=1) %>% distinct(HADM_ID)
cpr$CPR = TRUE
# print(kable(data) %>% kable_styling(bootstrap_options = 'striped'))
```
```{r}
bun_sodium = read.csv('data/DATA_MASTER.csv') %>% select(HADM_ID, BUN, SODIUM)
```


```{r}
joined = left_join(cohort, bnp) %>% left_join(diuretic) %>% left_join(blocker) %>% left_join(cpr) %>% left_join(bun_sodium)
joined$DIURETIC[is.na(joined$DIURETIC)] = 0
joined$BETABLOCKERS[is.na(joined$BETABLOCKERS)] = 0
joined$CPR[is.na(joined$CPR)] = FALSE
joined$BNP[is.na(joined$BNP)] = mean(bnp$BNP, na.rm = TRUE)
joined$BUN[is.na(joined$BUN)] = mean(bun_sodium$BUN, na.rm = TRUE)
joined$SODIUM[is.na(joined$SODIUM)] = mean(bun_sodium$SODIUM, na.rm = TRUE)
```
```{r}
joined$ESCAPE_SCORE = 0
joined$ESCAPE_SCORE = joined$ESCAPE_SCORE + as.numeric(joined$AGE > 70)
joined$ESCAPE_SCORE = joined$ESCAPE_SCORE + as.numeric(joined$BUN > 40)
joined$ESCAPE_SCORE = joined$ESCAPE_SCORE + as.numeric(joined$BUN > 90)
joined$ESCAPE_SCORE = joined$ESCAPE_SCORE + as.numeric(joined$SODIUM < 130)
joined$ESCAPE_SCORE = joined$ESCAPE_SCORE + as.numeric(joined$CPR) * 2
joined$ESCAPE_SCORE = joined$ESCAPE_SCORE + as.numeric(joined$DIURETIC > 240)
joined$ESCAPE_SCORE = joined$ESCAPE_SCORE + as.numeric(joined$BETABLOCKERS < 0.0001)
joined$ESCAPE_SCORE = joined$ESCAPE_SCORE + as.numeric(joined$BNP > 500)
joined$ESCAPE_SCORE = joined$ESCAPE_SCORE + as.numeric(joined$BNP > 1300) * 3
write.csv(joined, 'data/ESCAPE_data.csv')
```




